### ISSUE TITLE
クリエイティブについて

### ISSUE THREAD

**Issue by sing-draw** [t-hrhs/struck_out#47]
@t-hrhs 
現在遊び方ページおよびトップ画面を鋭意制作中だが、それらをgit管理下。
いざとなったらここを参照
https://github.com/sing-draw/struck_out_creative

**Comment by sing-draw** [comment]
@t-hrhs 
How to playの素材を以下にアップしています。
https://github.com/sing-draw/struck_out_creative/tree/master/share

**Comment by t-hrhs** [comment]
既にこちらのrepositoryでも対応したのでclose
